-- ============================================
-- SECURITE ET RBAC (Role-Based Access Control)
-- Healthcare Patient Records System
-- ============================================

ALTER SESSION SET "_ORACLE_SCRIPT"=true;
-- ============================================
-- ETAPE 1 : CREER LES ROLES
-- ============================================

-- Role ADMIN : Acces complet
CREATE ROLE ROLE_ADMIN;

-- Role MEDECIN : Consultation et modification des dossiers patients
CREATE ROLE ROLE_MEDECIN;

-- Role RECEPTIONNISTE : Gestion des RDV et facturation
CREATE ROLE ROLE_RECEPTIONNISTE;

-- Role PATIENT : Consultation de son propre dossier (lecture seule)
CREATE ROLE ROLE_PATIENT;

PROMPT Roles crees avec succes

-- ============================================
-- ETAPE 2 : ATTRIBUER LES PRIVILEGES - ADMIN
-- ============================================

-- ADMIN a tous les privileges
GRANT ALL ON PATIENT TO ROLE_ADMIN;
GRANT ALL ON MEDECIN TO ROLE_ADMIN;
GRANT ALL ON DEPARTEMENT TO ROLE_ADMIN;
GRANT ALL ON RENDEZ_VOUS TO ROLE_ADMIN;
GRANT ALL ON CONSULTATION TO ROLE_ADMIN;
GRANT ALL ON TRAITEMENT TO ROLE_ADMIN;
GRANT ALL ON MEDICAMENT TO ROLE_ADMIN;
GRANT ALL ON FACTURE TO ROLE_ADMIN;
GRANT ALL ON UTILISATEUR TO ROLE_ADMIN;
GRANT ALL ON AUDIT_LOG TO ROLE_ADMIN;

-- Privileges sur les vues
GRANT SELECT ON V_PLANNING_MEDECIN TO ROLE_ADMIN;
GRANT SELECT ON V_FACTURES_IMPAYEES TO ROLE_ADMIN;
GRANT SELECT ON V_HISTORIQUE_PATIENT TO ROLE_ADMIN;
GRANT SELECT ON V_TRAITEMENTS_PRESCRITS TO ROLE_ADMIN;
GRANT SELECT ON V_STATISTIQUES_MEDECINS TO ROLE_ADMIN;
GRANT SELECT ON V_STOCK_MEDICAMENTS TO ROLE_ADMIN;
GRANT SELECT ON V_REVENUS_JOURNALIERS TO ROLE_ADMIN;
GRANT SELECT ON V_PATIENTS_ACTIFS TO ROLE_ADMIN;
GRANT SELECT ON V_RDV_DU_JOUR TO ROLE_ADMIN;
GRANT SELECT ON V_DASHBOARD_GLOBAL TO ROLE_ADMIN;

-- Privileges sur les sequences
GRANT SELECT ON seq_patient TO ROLE_ADMIN;
GRANT SELECT ON seq_medecin TO ROLE_ADMIN;
GRANT SELECT ON seq_departement TO ROLE_ADMIN;
GRANT SELECT ON seq_rdv TO ROLE_ADMIN;
GRANT SELECT ON seq_consultation TO ROLE_ADMIN;
GRANT SELECT ON seq_traitement TO ROLE_ADMIN;
GRANT SELECT ON seq_medicament TO ROLE_ADMIN;
GRANT SELECT ON seq_facture TO ROLE_ADMIN;
GRANT SELECT ON seq_utilisateur TO ROLE_ADMIN;

-- Privileges sur les procedures et fonctions
GRANT EXECUTE ON SP_INSERT_PATIENT TO ROLE_ADMIN;
GRANT EXECUTE ON SP_INSERT_MEDECIN TO ROLE_ADMIN;
GRANT EXECUTE ON SP_CREER_RDV TO ROLE_ADMIN;
GRANT EXECUTE ON SP_MODIFIER_STATUT_RDV TO ROLE_ADMIN;
GRANT EXECUTE ON SP_CREER_CONSULTATION TO ROLE_ADMIN;
GRANT EXECUTE ON SP_PRESCRIRE_MEDICAMENT TO ROLE_ADMIN;
GRANT EXECUTE ON SP_ENREGISTRER_PAIEMENT TO ROLE_ADMIN;

GRANT EXECUTE ON FN_CALCULER_AGE TO ROLE_ADMIN;
GRANT EXECUTE ON FN_VERIFIER_DISPO_MEDECIN TO ROLE_ADMIN;
GRANT EXECUTE ON FN_GENERER_NUM_FACTURE TO ROLE_ADMIN;
GRANT EXECUTE ON FN_CALCULER_MONTANT_MEDICAMENTS TO ROLE_ADMIN;

PROMPT Privileges ADMIN attribues

-- ============================================
-- ETAPE 3 : ATTRIBUER LES PRIVILEGES - MEDECIN
-- ============================================

-- Lecture sur toutes les tables
GRANT SELECT ON PATIENT TO ROLE_MEDECIN;
GRANT SELECT ON MEDECIN TO ROLE_MEDECIN;
GRANT SELECT ON DEPARTEMENT TO ROLE_MEDECIN;
GRANT SELECT ON RENDEZ_VOUS TO ROLE_MEDECIN;
GRANT SELECT ON MEDICAMENT TO ROLE_MEDECIN;

-- Modification sur consultations et traitements
GRANT SELECT, INSERT, UPDATE ON CONSULTATION TO ROLE_MEDECIN;
GRANT SELECT, INSERT, UPDATE ON TRAITEMENT TO ROLE_MEDECIN;

-- Lecture seule sur factures
GRANT SELECT ON FACTURE TO ROLE_MEDECIN;

-- Acces aux vues
GRANT SELECT ON V_PLANNING_MEDECIN TO ROLE_MEDECIN;
GRANT SELECT ON V_HISTORIQUE_PATIENT TO ROLE_MEDECIN;
GRANT SELECT ON V_TRAITEMENTS_PRESCRITS TO ROLE_MEDECIN;
GRANT SELECT ON V_RDV_DU_JOUR TO ROLE_MEDECIN;
GRANT SELECT ON V_STOCK_MEDICAMENTS TO ROLE_MEDECIN;

-- Procedures et fonctions
GRANT EXECUTE ON SP_CREER_CONSULTATION TO ROLE_MEDECIN;
GRANT EXECUTE ON SP_PRESCRIRE_MEDICAMENT TO ROLE_MEDECIN;
GRANT EXECUTE ON SP_MODIFIER_STATUT_RDV TO ROLE_MEDECIN;

GRANT EXECUTE ON FN_CALCULER_AGE TO ROLE_MEDECIN;
GRANT EXECUTE ON FN_VERIFIER_STOCK_MEDICAMENT TO ROLE_MEDECIN;
GRANT EXECUTE ON FN_OBTENIR_NOM_COMPLET_PATIENT TO ROLE_MEDECIN;

-- Sequences necessaires
GRANT SELECT ON seq_consultation TO ROLE_MEDECIN;
GRANT SELECT ON seq_traitement TO ROLE_MEDECIN;

PROMPT Privileges MEDECIN attribues

-- ============================================
-- ETAPE 4 : ATTRIBUER LES PRIVILEGES - RECEPTIONNISTE
-- ============================================

-- Lecture sur la plupart des tables
GRANT SELECT ON PATIENT TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON MEDECIN TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON DEPARTEMENT TO ROLE_RECEPTIONNISTE;

-- Gestion complete des RDV
GRANT SELECT, INSERT, UPDATE, DELETE ON RENDEZ_VOUS TO ROLE_RECEPTIONNISTE;

-- Gestion des patients
GRANT SELECT, INSERT, UPDATE ON PATIENT TO ROLE_RECEPTIONNISTE;

-- Gestion complete des factures
GRANT SELECT, INSERT, UPDATE ON FACTURE TO ROLE_RECEPTIONNISTE;

-- Lecture seule sur consultations
GRANT SELECT ON CONSULTATION TO ROLE_RECEPTIONNISTE;

-- Acces aux vues
GRANT SELECT ON V_PLANNING_MEDECIN TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON V_FACTURES_IMPAYEES TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON V_PATIENTS_ACTIFS TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON V_RDV_DU_JOUR TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON V_DASHBOARD_GLOBAL TO ROLE_RECEPTIONNISTE;

-- Procedures et fonctions
GRANT EXECUTE ON SP_INSERT_PATIENT TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON SP_CREER_RDV TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON SP_MODIFIER_STATUT_RDV TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON SP_ENREGISTRER_PAIEMENT TO ROLE_RECEPTIONNISTE;

GRANT EXECUTE ON FN_CALCULER_AGE TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON FN_VERIFIER_DISPO_MEDECIN TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON FN_GENERER_NUM_FACTURE TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON FN_OBTENIR_NOM_COMPLET_PATIENT TO ROLE_RECEPTIONNISTE;
GRANT EXECUTE ON FN_OBTENIR_NOM_COMPLET_MEDECIN TO ROLE_RECEPTIONNISTE;

-- Sequences necessaires
GRANT SELECT ON seq_patient TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON seq_rdv TO ROLE_RECEPTIONNISTE;
GRANT SELECT ON seq_facture TO ROLE_RECEPTIONNISTE;

PROMPT Privileges RECEPTIONNISTE attribues

-- ============================================
-- ETAPE 5 : ATTRIBUER LES PRIVILEGES - PATIENT
-- ============================================

-- Lecture seule sur son propre dossier (implementation via VPD plus tard)
GRANT SELECT ON PATIENT TO ROLE_PATIENT;
GRANT SELECT ON RENDEZ_VOUS TO ROLE_PATIENT;
GRANT SELECT ON CONSULTATION TO ROLE_PATIENT;
GRANT SELECT ON TRAITEMENT TO ROLE_PATIENT;
GRANT SELECT ON MEDICAMENT TO ROLE_PATIENT;
GRANT SELECT ON FACTURE TO ROLE_PATIENT;

-- Acces aux vues (filtre par patient via VPD)
GRANT SELECT ON V_HISTORIQUE_PATIENT TO ROLE_PATIENT;

-- Fonctions utilitaires
GRANT EXECUTE ON FN_CALCULER_AGE TO ROLE_PATIENT;

PROMPT Privileges PATIENT attribues



-- ============================================
-- ETAPE 7 : POLITIQUE DE SECURITE SUPPLEMENTAIRE
-- ============================================

-- Activer l'audit sur les tables sensibles
AUDIT SELECT, INSERT, UPDATE, DELETE ON PATIENT BY ACCESS;
AUDIT SELECT, INSERT, UPDATE, DELETE ON CONSULTATION BY ACCESS;
AUDIT SELECT, INSERT, UPDATE, DELETE ON FACTURE BY ACCESS;
AUDIT ALL ON UTILISATEUR BY ACCESS;

PROMPT Audit active sur les tables sensibles

-- ============================================
-- ETAPE 8 : ROW LEVEL SECURITY (RLS) - EXEMPLE
-- ============================================

-- Creer une politique VPD pour les patients
-- Les patients ne peuvent voir que leurs propres donnees

CREATE OR REPLACE FUNCTION fn_patient_security_policy(
    schema_name IN VARCHAR2,
    table_name IN VARCHAR2
)
RETURN VARCHAR2
AS
    v_predicate VARCHAR2(2000);
    v_user VARCHAR2(100);
    v_id_patient NUMBER;
BEGIN
    -- Recuperer l'utilisateur courant
    v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
    
    -- Si c'est un ADMIN ou MEDECIN ou RECEPTIONNISTE, pas de filtre
    IF v_user IN ('ADMIN_USER', 'DR_ALAMI', 'RECEPTIONNISTE') THEN
        RETURN '';
    END IF;
    
    
    v_predicate := 'id_patient = (SELECT id_patient FROM UTILISATEUR WHERE username = SYS_CONTEXT(''USERENV'', ''SESSION_USER''))';
    
    RETURN v_predicate;
    
EXCEPTION
    WHEN OTHERS THEN
        -- En cas d'erreur, bloquer l'acces
        RETURN '1=0';
END;
/



PROMPT Politique de securite RLS definie (non activee par defaut)

-- ============================================
-- RESUME DES PRIVILEGES
-- ============================================

PROMPT 
PROMPT ========================================
PROMPT RESUME DES ROLES ET PRIVILEGES
PROMPT ========================================
PROMPT 
PROMPT ROLE_ADMIN:
PROMPT   - Acces complet a toutes les tables
PROMPT   - Toutes les procedures et fonctions
PROMPT   - Toutes les vues
PROMPT   - Gestion des utilisateurs
PROMPT 
PROMPT ROLE_MEDECIN:
PROMPT   - Lecture: Patients, Medecins, Departements, RDV, Medicaments
PROMPT   - Modification: Consultations, Traitements
PROMPT   - Procedures: Creer consultation, Prescrire medicament
PROMPT   - Vues: Planning, Historique patient, Stock medicaments
PROMPT 
PROMPT ROLE_RECEPTIONNISTE:
PROMPT   - Lecture: Patients, Medecins, Departements, Consultations
PROMPT   - Modification: Patients, RDV, Factures
PROMPT   - Procedures: Creer patient, Creer RDV, Enregistrer paiement
PROMPT   - Vues: Planning, Factures impayees, Dashboard
PROMPT 
PROMPT ROLE_PATIENT:
PROMPT   - Lecture seule sur son propre dossier (via RLS)
PROMPT   - Vue: Historique patient (filtre)
PROMPT 